version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zigral
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=orchestrator
      - DATABASE_URL=postgresql://user:password@postgres:5432/zigral
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./checkpoints:/app/checkpoints
    depends_on:
      postgres:
        condition: service_healthy

  context-manager:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_NAME=context-manager
      - DATABASE_URL=postgresql://user:password@postgres:5432/zigral
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 