version: '3.8'

services:
  kasm:
    image: kasmweb/desktop:1.14.0
    ports:
      - "6901:6901"  # Kasm web interface
    environment:
      - VNC_PW=password123  # Change this in production
      - KASM_USER=zigral
    volumes:
      - ./workspace:/workspace
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
    networks:
      - zigral_network

  orchestrator:
    build: .
    depends_on:
      - kasm
      - postgres
    environment:
      - VIRTUAL_DESKTOP_MODE=True
      - DATABASE_URL=postgresql://user:password@postgres:5432/zigral
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    networks:
      - zigral_network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zigral
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - zigral_network

volumes:
  postgres_data:

networks:
  zigral_network:
    driver: bridge 