#!/bin/bash

export DISPLAY=:99

# Start Xvfb
Xvfb :99 -screen 0 1280x720x24 &
sleep 2

# Start LXDE
exec startlxde &

# Start x11vnc
x11vnc -display :99 -rfbport 5900 -forever -nopw -listen localhost -shared -xkb
